CREATE TABLE [auth].[USER_ROLES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[RoleID] [int] NOT NULL,
	[Created] [datetime] NOT NULL,
        [CreateUser] [varchar](50) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](50) NOT NULL,
  CONSTRAINT [PK_USER_ROLES] PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_USER_ROLES_UserID_RoleID] UNIQUE NONCLUSTERED ([UserID] ASC, [RoleID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [auth].[USER_ROLES] ADD  CONSTRAINT [DF_USER_ROLES_CREATED]  DEFAULT (getdate()) FOR [Created];
ALTER TABLE [auth].[USER_ROLES] ADD  CONSTRAINT [DF_USER_ROLES_CREATEUSER]  DEFAULT ('ROOT') FOR [CreateUser];
ALTER TABLE [auth].[USER_ROLES] ADD  CONSTRAINT [DF_USER_ROLES_UPDATED]  DEFAULT (getdate()) FOR [Updated];
ALTER TABLE [auth].[USER_ROLES] ADD  CONSTRAINT [DF_USER_ROLES_UPDATEUSER]  DEFAULT ('ROOT') FOR [UpdateUser];
ALTER TABLE [auth].[USER_ROLES] WITH CHECK ADD CONSTRAINT [FK_USER_ROLES_RoleID] FOREIGN KEY([RoleID])
REFERENCES [auth].[ROLES] ([ID]);
ALTER TABLE [auth].[USER_ROLES] CHECK CONSTRAINT [FK_USER_ROLES_RoleID];
ALTER TABLE [auth].[USER_ROLES] WITH CHECK ADD  CONSTRAINT [FK_USER_ROLES_UserID] FOREIGN KEY([UserID])
REFERENCES [auth].[USERS] ([ID]);
ALTER TABLE [auth].[USER_ROLES] CHECK CONSTRAINT [FK_USER_ROLES_UserID];
