CREATE TABLE [auth].[USERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GUID] [varchar](50) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Password] [varchar](255) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[Created] [datetime] NOT NULL,
        [CreateUser] [varchar](50) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](50) NOT NULL,
  CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_USERS_GUID] UNIQUE NONCLUSTERED ([GUID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_USERS_USERNAME] UNIQUE NONCLUSTERED ([UserName] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [auth].[USERS] ADD  CONSTRAINT [DF_USERS_GUID]  DEFAULT (newid()) FOR [GUID];
ALTER TABLE [auth].[USERS] ADD  CONSTRAINT [DF_USERS_ISACTIVE]  DEFAULT ((0)) FOR [IsActive];
ALTER TABLE [auth].[USERS] ADD  CONSTRAINT [DF_USERS_CREATED]  DEFAULT (getdate()) FOR [Created];
ALTER TABLE [auth].[USERS] ADD  CONSTRAINT [DF_USERS_CREATEUSER]  DEFAULT ('ROOT') FOR [CreateUser];
ALTER TABLE [auth].[USERS] ADD  CONSTRAINT [DF_USERS_UPDATED]  DEFAULT (getdate()) FOR [Updated];
ALTER TABLE [auth].[USERS] ADD  CONSTRAINT [DF_USERS_UPDATEUSER]  DEFAULT ('ROOT') FOR [UpdateUser];
ALTER TABLE [auth].[USERS]  WITH CHECK ADD  CONSTRAINT [CHK_USERS_ROOT] CHECK  (([ID]<>(1) OR [ID]=(1) AND [GUID]='ROOT'));
ALTER TABLE [auth].[USERS] CHECK CONSTRAINT [CHK_USERS_ROOT];

-- add root user
INSERT INTO [auth].[USERS]
(GUID,Username,Password,FirstName,LastName,IsActive)
VALUES ('ROOT','engineering@educationplannerbc.ca','$2a$10$u2IpPpnY/.ANzVtWqQvmqOdZKwF9AfX2p/dgZVVSbMy/yaAzHx7uW','EPBC','Root User',1);
