CREATE TABLE [auth].[ROLES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GUID] [varchar](50) NOT NULL,
        [TenantID] [int] NOT NULL,   
	[Name] [varchar](40) NOT NULL,
  	[Description] [nvarchar](200) NOT NULL,
	[Created] [datetime] NOT NULL,
        [CreateUser] [varchar](50) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](50) NOT NULL,
  CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_ROLES_GUID] UNIQUE NONCLUSTERED ([GUID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [auth].[ROLES] ADD  CONSTRAINT [DF_ROLES_GUID]  DEFAULT (newid()) FOR [GUID];
ALTER TABLE [auth].[ROLES] ADD  CONSTRAINT [DF_ROLES_Created]  DEFAULT (getdate()) FOR [Created];
ALTER TABLE [auth].[ROLES] ADD  CONSTRAINT [DF_ROLES_CreateUser]  DEFAULT ('ROOT') FOR [CreateUser];
ALTER TABLE [auth].[ROLES] ADD  CONSTRAINT [DF_ROLES_Updated]  DEFAULT (getdate()) FOR [Updated];
ALTER TABLE [auth].[ROLES] ADD  CONSTRAINT [DF_ROLES_UpdatedUser]  DEFAULT ('ROOT') FOR [UpdateUser];
ALTER TABLE [auth].[ROLES]  WITH CHECK ADD  CONSTRAINT [FK_ROLES_TenantID] FOREIGN KEY([TenantID])
REFERENCES [auth].[TENANTS] ([ID]);
ALTER TABLE [auth].[ROLES] CHECK CONSTRAINT [FK_ROLES_TenantID];

