CREATE TABLE [auth].[CATEGORIES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](50) NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Created] [datetime] NOT NULL,
        [CreateUser] [varchar](50) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](50) NOT NULL,
  CONSTRAINT [PK_CATEGORIES] PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_CATEGORIES_Code] UNIQUE NONCLUSTERED ([Code] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [auth].[CATEGORIES] ADD  CONSTRAINT [DF_CATEGORIES_Created]  DEFAULT (getdate()) FOR [Created];
ALTER TABLE [auth].[CATEGORIES] ADD  CONSTRAINT [DF_CATEGORIES_CreateUser]  DEFAULT ('ROOT') FOR [CreateUser];
ALTER TABLE [auth].[CATEGORIES] ADD  CONSTRAINT [DF_CATEGORIES_Updated]  DEFAULT (getdate()) FOR [Updated];
ALTER TABLE [auth].[CATEGORIES] ADD  CONSTRAINT [DF_CATEGORIES_UpdateUser]  DEFAULT ('ROOT') FOR [UpdateUser];

