CREATE TABLE [auth].[INVITATIONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](255) NOT NULL,
	[Token] [uniqueidentifier] NOT NULL,
	[Status] [varchar](20) NOT NULL,
	[Created] [datetime] NOT NULL,
	[CreateUser] [varchar](50) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](50) NOT NULL,
  CONSTRAINT [PK_INVITATIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_INVITATIONS_Email] UNIQUE NONCLUSTERED ([Email] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [auth].[INVITATIONS] ADD  CONSTRAINT [DF_INVITATIONS_Status]  DEFAULT ('PENDING') FOR [Status];
ALTER TABLE [auth].[INVITATIONS] ADD  CONSTRAINT [DF_INVITATIONS_Created]  DEFAULT (getdate()) FOR [Created];
ALTER TABLE [auth].[INVITATIONS] ADD  CONSTRAINT [DF_INVITATIONS_CreateUser]  DEFAULT ('ROOT') FOR [CreateUser];
ALTER TABLE [auth].[INVITATIONS] ADD  CONSTRAINT [DF_INVITATIONS_Updated]  DEFAULT (getdate()) FOR [Updated];
ALTER TABLE [auth].[INVITATIONS] ADD  CONSTRAINT [DF_INVITATIONS_UpdateUser]  DEFAULT ('ROOT') FOR [UpdateUser];

