CREATE TABLE [auth].[HOST_OVERRIDES] (
        [ID] [int] IDENTITY(1,1) NOT NULL,
	[HostID] [int] NOT NULL,
	[Permission] [varchar](16) NOT NULL,
        [Created] [datetime] NOT NULL,
        [CreateUser] [varchar](50) NOT NULL,
        [Updated] [datetime] NOT NULL,
        [UpdateUser] [varchar](50) NOT NULL,
  CONSTRAINT [PK_HOST_OVERRIDES] PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_HOST_OVERRIDES_HostID_Permission] UNIQUE NONCLUSTERED ([HostID] ASC, [Permission] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [auth].[HOST_OVERRIDES] ADD  CONSTRAINT [DF_HOST_OVERRIDES_Created]  DEFAULT (getdate()) FOR [Created];
ALTER TABLE [auth].[HOST_OVERRIDES] ADD  CONSTRAINT [DF_HOST_OVERRIDES_CreateUser]  DEFAULT ('ROOT') FOR [CreateUser];
ALTER TABLE [auth].[HOST_OVERRIDES] ADD  CONSTRAINT [DF_HOST_OVERRIDES_Updated]  DEFAULT (getdate()) FOR [Updated];
ALTER TABLE [auth].[HOST_OVERRIDES] ADD  CONSTRAINT [DF_HOST_OVERRIDES_UpdateUser]  DEFAULT ('ROOT') FOR [UpdateUser];
ALTER TABLE [auth].[HOST_OVERRIDES] WITH CHECK ADD CONSTRAINT [FK_HOST_OVERRIDES_HostID] FOREIGN KEY([HostID])
REFERENCES [auth].[HOSTS] ([ID]);
ALTER TABLE [auth].[HOST_OVERRIDES] CHECK CONSTRAINT [FK_HOST_OVERRIDES_HostID];
ALTER TABLE [auth].[HOST_OVERRIDES] ADD CONSTRAINT [CHK_HOST_OVERRIDES_Permission] CHECK ([Permission] = 'allow' OR [Permission] = 'deny');
