CREATE TABLE [auth].[HOST_CHECKS] (
        [ID] [int] IDENTITY(1,1) NOT NULL,
	[HostID] [int] NOT NULL,
	[CheckID] [int] NULL,
        [Created] [datetime] NOT NULL,
        [CreateUser] [varchar](50) NOT NULL,
        [Updated] [datetime] NOT NULL,
        [UpdateUser] [varchar](50) NOT NULL,
  CONSTRAINT [PK_HOST_CHECKS] PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
  CONSTRAINT [UK_HOST_CHECKS_HostID_CheckID] UNIQUE NONCLUSTERED ([HostID] ASC, CheckID ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [auth].[HOST_CHECKS] ADD  CONSTRAINT [DF_HOST_CHECKS_Created]  DEFAULT (getdate()) FOR [Created];
ALTER TABLE [auth].[HOST_CHECKS] ADD  CONSTRAINT [DF_HOST_CHECKS_CreateUser]  DEFAULT ('ROOT') FOR [CreateUser];
ALTER TABLE [auth].[HOST_CHECKS] ADD  CONSTRAINT [DF_HOST_CHECKS_Updated]  DEFAULT (getdate()) FOR [Updated];
ALTER TABLE [auth].[HOST_CHECKS] ADD  CONSTRAINT [DF_HOST_CHECKS_UpdateUser]  DEFAULT ('ROOT') FOR [UpdateUser];
ALTER TABLE [auth].[HOST_CHECKS] WITH CHECK ADD CONSTRAINT [FK_HOST_CHECKS_HostID] FOREIGN KEY([HostID])
REFERENCES [auth].[HOSTS] ([ID]);
ALTER TABLE [auth].[HOST_CHECKS] CHECK CONSTRAINT [FK_HOST_CHECKS_HostID];
ALTER TABLE [auth].[HOST_CHECKS] WITH CHECK ADD CONSTRAINT [FK_HOST_CHECKS_CheckID] FOREIGN KEY([CheckID])
REFERENCES [auth].[CHECKS] ([ID]);
ALTER TABLE [auth].[HOST_CHECKS] CHECK CONSTRAINT [FK_HOST_CHECKS_CheckID];
