apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- etc-pv.yaml
- etc-pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- middleware.yaml
# customize in overlay: - middleware.yaml
