#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.16

pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            - mkdir test-reports
            - go get -u bitbucket.org/_metalogic_/junit-report
            - go test tests/* -v 2>&1 | junit-report > test-reports/report.xml
            # Docker build
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t metalogic/forward-auth:latest .
            - docker push metalogic/forward-auth:latest
      - step:
          name: Lint code
          image: golangci/golangci-lint:v1.31.0
          script:
            - golangci-lint run -v
