apiVersion: v1
kind: PersistentVolume
metadata:
  name: CHANGE-ME-etc-forward-auth-volume
  labels:
    type: local
    app: forward-auth
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /CHANGE-ME/to/path/to/etc/forward-auth
  persistentVolumeReclaimPolicy: Retain
