apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-forward-auth-volume-claim
  labels:
    app: forward-auth
spec:
  volumeName: CHANGE-ME-etc-forward-auth-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
