package http

import (
	"net/http"

	fa "bitbucket.org/_metalogic_/forward-auth"
	_ "bitbucket.org/_metalogic_/forward-auth/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "bitbucket.org/_metalogic_/httptreemux-swagger"
	"github.com/dimfeld/httptreemux/v5"
)

// Handler ...
type Handler struct {
	service fa.Service
	handler *httptreemux.TreeMux
}

// ServeHTTP serves requests against the forward-auth API.
func (h *Handler) ServeHTTP(addr string) error {
	return http.ListenAndServe(addr, h.handler)
}

// NewHandler returns a new Handler for the servicej
func NewHandler(svc fa.Service, jwtHeader, userHeader, traceHeader string) *Handler {
	return &Handler{service: svc, handler: router(svc, jwtHeader, userHeader, traceHeader)}
}

// create the router for Service
func router(svc fa.Service, jwtHeader, userHeader, traceHeader string) *httptreemux.TreeMux {
	// initialize HTTP router
	treemux := httptreemux.New()
	api := treemux.NewGroup("/")
	api.GET("/admin/loglevel", LogLevel(svc))
	api.PUT("/admin/loglevel/:verbosity", SetLogLevel(svc))
	api.GET("/health", Health(svc))
	api.GET("/info", APIInfo(svc))
	api.GET("/stats", Stats(svc))
	api.GET("/admin/run", RunMode(svc))
	api.PUT("/admin/run/:mode", SetRunMode(svc))
	api.GET("/admin/tree", Tree(svc))
	api.GET("/block", Blocked(svc))
	api.POST("/block/:userGUID", Block(svc))
	api.DELETE("/block/:userGUID", Unblock(svc))
	api.GET("/auth", Auth(svc, jwtHeader, userHeader, traceHeader))
	api.GET("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("doc.json"), // The url pointing to API definition
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("#swagger-ui")))
	return treemux
}
