apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-forward-auth-volume
  labels:
    type: local
    app: forward-auth
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/Volumes/etc/forward-auth
  persistentVolumeReclaimPolicy: Retain
