# Forward authentication forward-auth host in cluster 
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-middleware
spec:
  forwardAuth:
    address: http://forward-auth-service.gtvets.svc.cluster.local:8080/auth
