apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../../../go/src/bitbucket.org/_metalogic_/forward-auth/manifests/base
#- https://bitbucket.org/_metalogic_/forward-auth/manifests?ref=kustomize
resources:
- etc-pv.yaml
- etc-pvc.yaml
- config.yaml
- secrets/kubeseal.json
patchesJson6902:
- target:
    kind: Middleware
    name: forward-auth-middleware
  path: middleware-patch.json
