SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [authz].[SYSTEMS]
GO

CREATE TABLE [authz].[SYSTEMS]
(
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[GUID] [varchar](36) NOT NULL,
	[Name] [varchar](128) NOT NULL,
	[Version] [int] NOT NULL,
	[Comment] [varchar](256) NOT NULL,
	[Created] [datetime] NOT NULL,
	[CreateUser] [varchar](36) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](36) NOT NULL,
) ON [PRIMARY]
GO

ALTER TABLE [authz].[SYSTEMS] ADD PRIMARY KEY CLUSTERED ([ID] ASC)
WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_GUID] DEFAULT (newid()) FOR [GUID]
GO
ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_Created] DEFAULT (getdate()) FOR [Created]
GO
ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_CreateUser] DEFAULT ('ROOT') FOR [CreateUser]
GO
ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_Updated] DEFAULT (getdate()) FOR [Updated]
GO
ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_UpdateUser] DEFAULT ('ROOT') FOR [UpdateUser]
GO

ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT UK_SYSTEMS_Version UNIQUE ([Version])
GO