SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [authz].[HOSTS]
GO

CREATE TABLE [authz].[HOSTS]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GUID] [varchar](36) NOT NULL,
	[GroupID] INT NOT NULL,
	[Hostname] [varchar](256) NOT NULL,
	[Created] [datetime] NOT NULL,
	[CreateUser] [varchar](36) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](36) NOT NULL,
) ON [PRIMARY]
GO

ALTER TABLE [authz].[HOSTS] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [authz].[HOSTS] ADD CONSTRAINT [DF_HOSTS_GUID] DEFAULT (newid()) FOR [GUID]
GO
ALTER TABLE [authz].[HOSTS] ADD CONSTRAINT [DF_HOSTS_Created] DEFAULT (getdate()) FOR [Created]
GO
ALTER TABLE [authz].[HOSTS] ADD CONSTRAINT [DF_HOSTS_CreateUser] DEFAULT ('ROOT') FOR [CreateUser]
GO
ALTER TABLE [authz].[HOSTS] ADD CONSTRAINT [DF_HOSTS_Updated] DEFAULT (getdate()) FOR [Updated]
GO
ALTER TABLE [authz].[HOSTS] ADD CONSTRAINT [DF_HOSTS_UpdateUser] DEFAULT ('ROOT') FOR [UpdateUser]
GO

ALTER TABLE [authz].[HOSTS] WITH CHECK ADD CONSTRAINT [FK_HOSTS_Group] FOREIGN KEY([GroupID])
REFERENCES [authz].[HOST_GROUPS] ([ID])
GO

ALTER TABLE [authz].[HOSTS] ADD CONSTRAINT UK_HOSTS_Hostname UNIQUE ("Hostname")
GO
