DROP TABLE IF EXISTS [authz].[PATHS]
GO
DROP TABLE IF EXISTS [authz].[CHECKS]
GO
DROP TABLE IF EXISTS [authz].[HOSTS]
GO
DROP TABLE IF EXISTS [authz].[HOSTGROUPS]
GO
DROP TABLE IF EXISTS [authz].[SYSTEMS]
GO
