-- +goose Up

CREATE TABLE [authz].[SYSTEMS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GUID] [varchar](36) NOT NULL,
	[Name] [varchar](128) NOT NULL,
	[Version] [int] NOT NULL,
	[Comment] [varchar](256) NOT NULL,
	[Created] [datetime] NOT NULL,
	[CreateUser] [varchar](36) NOT NULL,
	[Updated] [datetime] NOT NULL,
	[UpdateUser] [varchar](36) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [authz].[SYSTEMS] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [authz].[SYSTEMS] ADD  CONSTRAINT [UK_SYSTEMS_Version] UNIQUE NONCLUSTERED 
(
	[Version] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_authz_SYSTEMS_GUID] ON [authz].[SYSTEMS]
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_GUID]  DEFAULT (newid()) FOR [GUID];

ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_Created]  DEFAULT (getdate()) FOR [Created];

ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_CreateUser]  DEFAULT ('ROOT') FOR [CreateUser];

ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_Updated]  DEFAULT (getdate()) FOR [Updated];

ALTER TABLE [authz].[SYSTEMS] ADD CONSTRAINT [DF_SYSTEMS_UpdateUser]  DEFAULT ('ROOT') FOR [UpdateUser];

-- +goose Down

DROP TABLE [authz].[SYSTEMS];