apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- forward-auth-config.yaml
- secrets/forward-auth-kubeseal.json
patchesStrategicMerge:
- forward-auth-volume.yaml
